name: kalyan_ai_flutter_python
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: any
  tflite: any
  image_picker: any
  get: any
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: any
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true
